version: '3.9'
services:
  disk:
    hostname: localhost
    depends_on:
      - database

    restart: always

    build:
      context: app
      dockerfile: Dockerfile

    environment:
      DEBUG: ${DEBUG}
      PROJECT_NAME: ${PROJECT_NAME}
      SERVER_NAME: ${SERVER_NAME}

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}

    ports:
      - "80:2020"
    volumes:
      - ./app:/app
    privileged: true
    command: bash -c "python main.py"

  database:
    image: postgres:14.3
    volumes:
      - ./database/data2:/var/lib/postgresql/data
      - ./database/backups2:/backups
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}

    restart: always